-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 22-05-2015 a las 12:55:38
-- Versión del servidor: 5.6.21
-- Versión de PHP: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `videoclub`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `peliculas`
--

DROP TABLE IF EXISTS `peliculas`;
CREATE TABLE IF NOT EXISTS `peliculas` (
  `id_pelicula` int(11) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `año` int(11) NOT NULL,
  `pais` varchar(30) NOT NULL,
  `genero` varchar(100) NOT NULL,
  `imdb` varchar(50) NOT NULL,
  `clasificacion_imdb` varchar(100) NOT NULL,
  `resumen` varchar(2048) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `peliculas`
--

INSERT INTO `peliculas` (`id_pelicula`, `titulo`, `año`, `pais`, `genero`, `imdb`, `clasificacion_imdb`, `resumen`) VALUES
(1, 'Twelve Monkeys', 1995, 'USA', 'Suspenso, Ciencia Ficción, Misterio', '114746', '8,1  (404401 votos)', 'An unknown and lethal virus has wiped out five billion people in 1996. Only 1% of the population has survived by the year 2035, and is forced to live underground. A convict (James Cole) reluctantly volunteers to be sent back in time to 1996 to gather information about the origin of the epidemic (who he"s told was spread by a mysterious "Army of the Twelve Monkeys") and locate the virus before it mutates so that scientists can study it. Unfortunately Cole is mistakenly sent to 1990, six years earlier than expected, and is arrested and locked up in a mental institution, where he meets Dr. Kathryn Railly, a psychiatrist, and Jeffrey Goines, the insane son of a famous scientist and virus expert.'),
(2, '13 asesinos', 2010, 'Japan', 'Acción, Drama, Aventuras', '1436045', '7,6  (46077 votos)', 'In 1844, the peace of Feudal Japan is threatened by cruel Lord Naritsugu Matsudaira, who is politically rising and getting closer to his half-brother, the shogun. After the harakiri of the Namiya clan leader, samurai Shinzaemon Shimada is summoned by the shogun"s advisor Sir Doi of the Akashi Clan to listen to the tragedy of Makino Uneme, whose son and daughter-in-law have been murdered by Naritsugu. Then Sir Doi shows a woman with arms, legs and tongue severed by Naritsugu and she writes with her forearm a request to Shinza to slaughter Naritsugu and his samurai. Shinza promises to kill Naritsugu and he gathers eleven other samurais and plots a plan to attack Naritsugu in his trip back to the Akashi land. But the cunning samurai Hanbei Kitou that is responsible for the security of his master foresees Shinza"s intent. Shinza decides to go with his samurai through the mountain, where they find the hunter Koyata that guides them off the mountain and joins the group. Now the thirteen men...'),
(3, 'Trabajo basura', 1999, 'USA', 'Comedia', '151804', '7,8  (181721 votos)', 'In the Initech office, the insecure Peter Gibbons hates his job and the abusive Division VP Bill Lumbergh that has just hired two consultants to downsize the company. His best friends are the software engineers Michael Bolton and Samir Nagheenanajar that also hate Initech, and his next door neighbor Lawrence. His girlfriend Anne is cheating on him but she convinces Peter to visit the hypnotherapist Dr. Swanson. Peter tells how miserable his life is and Dr. Swanson hypnotizes him and he goes into a state of ecstasy. However, Dr. Swanson dies immediately after giving the hypnotic suggestion to Peter. He dates the waitress Joanna and changes his attitude in the company, being promoted by the consultants. When he discovers that Michael and Samir will be fired, they decide to plant a virus in the account system to embezzle fraction of cents in each financial operation into Peter"s account. However Michael commits a mistake in the software and instead of decimals, they steal a large amount....'),
(4, '300: Rise of an Empire', 2014, 'USA', 'Acción, Drama, Bélica, Fantasía', '1253863', '6,3  (188369 votos)', 'After its victory over Leonidas" 300, the Persian Army under the command of Xerxes marches towards the major Greek city-states. The Democratic city of Athens, first on the path of Xerxes" army, bases its strength on its fleet, led by admiral Themistocles. Themistocles is forced to an unwilling alliance with the traditional rival of Athens, oligarchic Sparta whose might lies with its superior infantry troops. But Xerxes still reigns supreme in numbers over sea and land.'),
(5, '47 Ronin', 2013, 'USA', 'Acción, Aventuras, Drama, Fantasía', '1335975', '6,3  (101859 votos)', 'While hunting in the forest, Lord Asano of Ako and his samurai find a young half-breed and take him with them to live in the castle. Several years later, Lord Asano holds a tournament to welcome the Shogun to Ako. The night after the tournament, Lord Asano is bewitched into hurting Lord Kira of Nagato, and is punished into committing seppuku by the Shogun. Realizing that it was a Lord Kira"s evil plot, the samurais and the half-breed sets out for revenge against the Shogun"s order.'),
(7, 'After Earth', 2013, 'USA', 'Acción, Aventuras, Ciencia Ficción', '1815862', '5,0  (142193 votos)', 'One thousand years after cataclysmic events forced humanity"s escape from Earth, Nova Prime has become mankind"s new home. Legendary General Cypher Raige returns from an extended tour of duty to his estranged family, ready to be a father to his 13-year-old son, Kitai. When an asteroid storm damages Cypher and Kitai"s craft, they crash-land on a now unfamiliar and dangerous Earth. As his father lies dying in the cockpit, Kitai must trek across the hostile terrain to recover their rescue beacon. His whole life, Kitai has wanted nothing more than to be a soldier like his father. Today, he gets his chance.'),
(8, 'Alexander and the Terrible, Horrible, No Good, Very Bad Day', 2014, 'USA', 'Comedia, Familiar', '1698641', '6,2  (19215 votos)', 'For 12 year old Alexander Cooper, everyday is a bad day. And his family thinks he"s being silly because they never have a bad day. On the day before his 12th birthday party, he learns that another boy is having a party of his own and everyone is going to it. And another kid punks him online. So at midnight of his birthday, he wishes that his whole family can have a bad day. And things for the whole family go bad, his mom"s car is broken so they have to share a car, his sister has a cold and has to go on stage, his older brother, who"s hoping to get his driver"s license and to bring his girlfriend to the prom, has to deal with his girlfriend"s snootiness and fails to get his license, his mom has a crisis at work which could cost her her job, and his dad who has a job interview has to bring his younger brother with him but because his pacifier is broken he can"t stop crying. Alex feels responsible.'),
(9, 'Alien', 1979, 'USA', 'Terror, Ciencia Ficción', '78748', '8,5  (479539 votos)', 'A commercial crew aboard the deep space towing vessel, Nostromo is on its way home when they pick an SOS warning from a distant planet. What they don"t know is that the SOS warning is not like any other ordinary warning call. Picking up the signal, the crew realize that they are not alone on the spaceship when an alien stowaway is on the cargo ship.'),
(10, 'Aliens', 1986, 'USA', 'Acción, Suspenso, Ciencia Ficción, Aventuras', '90605', '8,4  (422809 votos)', 'Fifty seven years after Ellen Ripley survived her disastrous ordeal, her escape vessel is recovered after drifting across the galaxy as she slept in cryogenic stasis. Back on earth, nobody believed her story about the "Aliens" on the planet LV-426. After the "Company" orders the colony on LV-426 to investigate, however, all communication with the colony is lost. The Company enlists Ripley to aid a team of tough, rugged space marines on a rescue mission to the now partially terraformed planet to find out if there are aliens or survivors. As the mission unfolds, Ripley will be forced to come to grips with her worst nightmare, but even as she does, she finds that the worst is yet to come.'),
(11, 'Amanece, que no es poco', 1989, 'Spain', 'Comedia', '94641', '7,6  (1649 votos)', 'A village and the crazy situations encountered by their citizens.'),
(12, 'American Sniper', 2014, 'USA', 'Acción, Suspenso, Bélica, Biográficas', '2179136', '7,4  (196205 votos)', 'Chris Kyle was nothing more than a Texan man who wanted to become a cowboy, but in his thirties he found out that maybe his life needed something different, something where he could express his real talent, something that could help America in its fight against terrorism. So he joined the SEALs in order to become a sniper. After marrying, Kyle and the other members of the team are called for their first tour of Iraq. Kyle"s struggle isn"t with his missions, but about his relationship with the reality of the war and, once returned at home, how he manages to handle it with his urban life, his wife and kids.'),
(13, 'Appleseed Alpha', 2014, 'Japan', 'Acción, Ciencia Ficción, Animación', '3638012', '6,6  (4504 votos)', 'Based on the comic book by the creator of Ghost in the Shell, a young female soldier Deunan and her cyborg partner Briareos survive through the post World War 3 apocalyptic New York in search of human"s future hope, the legendary city of Olympus.'),
(14, 'Asterix and Obelix: Mansion of the Gods', 2014, 'France', 'Comedia, Aventuras, Animación, Familiar', '3759416', '7,0  (2313 votos)', 'In order to wipe out the Gaulish village by any means necessary, Caesar plans to absorb the villagers into Roman culture by having an estate built next to the village to start a new Roman colony.'),
(15, 'Airplane!', 1980, 'USA', 'Comedia', '80339', '7,8  (142168 votos)', 'Still craving for the love of his life, Ted Striker follows Elaine onto the flight that she is working on as a member of the cabin crew. Elaine doesn"t want to be with Ted anymore, but when the crew and passengers fall ill from food poisoning, all eyes are on Ted.'),
(16, 'Austin Powers: International Man of Mystery', 1997, 'USA', 'Comedia, Policíaca, Ciencia Ficción', '118655', '7,0  (165350 votos)', 'Austin Powers is a 60"s spy who is cryonically frozen and released in the 1990"s. The world is a very different place for Powers. Unfortunately for Austin, everyone is no longer sex-mad. Although he may be in a different decade, his mission is still the same. He has teamed up with Vanessa Kensington to stop the evil Dr. Evil, who was also frozen in the past. Dr. Evil stole a nuclear weapon and is demanding a payment of (when he realises its the 90"s) 100 billion dollars. Can Austin Powers stop this madman? or will he caught up with Evil"s henchman, with names like Alotta Fagina and Random Task? Only time will tell!'),
(17, 'Avatar', 2009, 'USA', 'Acción, Aventuras, Fantasía, Ciencia Ficción', '499549', '7,9  (780646 votos)', 'When his brother is killed in a robbery, paraplegic Marine Jake Sully decides to take his place in a mission on the distant world of Pandora. There he learns of greedy corporate figurehead Parker Selfridge"s intentions of driving off the native humanoid "Na"vi" in order to mine for the precious material scattered throughout their rich woodland. In exchange for the spinal surgery that will fix his legs, Jake gathers intel for the cooperating military unit spearheaded by gung-ho Colonel Quaritch, while simultaneously attempting to infiltrate the Na"vi people with the use of an "avatar" identity. While Jake begins to bond with the native tribe and quickly falls in love with the beautiful alien Neytiri, the restless Colonel moves forward with his ruthless extermination tactics, forcing the soldier to take a stand - and fight back in an epic battle for the fate of Pandora.'),
(18, 'Planes: Fire & Rescue', 2014, 'USA', 'Comedia, Aventuras, Animación, Familiar', '2980706', '5,9  (9532 votos)', 'When world-famous air racer Dusty learns that his engine is damaged and he may never race again, he must shift gears and is launched into the world of aerial firefighting. Dusty joins forces with veteran fire and rescue helicopter Blade Ranger and his team, a bunch of all-terrain vehicles known as The Smokejumpers. Together, the fearless team battles a massive wildfire, and Dusty learns what it takes to become a true hero.'),
(19, 'Batman: The Dark Knight', 2008, 'UK', 'Acción, Ciencia Ficción, Aventuras, Cortos', '2098632', '8,3  (1774 votos)', ''),
(21, 'Batman Begins', 2005, 'USA', 'Acción, Aventuras', '372784', '8,3  (817360 votos)', 'When his parents were killed, millionaire playboy Bruce Wayne relocates to Asia when he is mentored by Henri Ducard and Ra"s Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as "Batman". But it doesn"t stay quiet for long.'),
(23, 'Big Hero 6', 2014, 'USA', 'Acción, Ciencia Ficción, Comedia, Aventuras, Animación, Familiar', '2245084', '7,9  (166340 votos)', 'From Walt Disney Animation Studios, the team behind "Frozen" and "Wreck-It Ralph," comes "Big Hero 6," an action-packed comedy-adventure about the special bond that develops between Baymax, a plus-sized inflatable robot, and prodigy Hiro Hamada. When a devastating event befalls the city of San Fransokyo and catapults Hiro into the midst of danger, he turns to Baymax and his close friends adrenaline junkie Go Go Tomago, neatnik Wasabi, chemistry whiz Honey Lemon and fanboy Fred. Determined to uncover the mystery, Hiro transforms his friends into a band of high-tech heroes called "Big Hero 6."'),
(25, 'Brave', 2012, 'USA', 'Comedia, Aventuras, Fantasía, Animación, Familiar', '1217209', '7,2  (225758 votos)', 'Set in Scotland in a rugged and mythical time, "Brave" features Merida, an aspiring archer and impetuous daughter of royalty. Merida makes a reckless choice that unleashes unintended peril and forces her to spring into action to set things right.'),
(26, 'Captain America: The First Avenger', 2011, 'USA', 'Acción, Ciencia Ficción, Aventuras', '458339', '6,8  (403424 votos)', 'It is 1942, America has entered World War II, and sickly but determined Steve Rogers is frustrated at being rejected yet again for military service. Everything changes when Dr. Erskine recruits him for the secret Project Rebirth. Proving his extraordinary courage, wits and conscience, Rogers undergoes the experiment and his weak body is suddenly enhanced into the maximum human potential. When Dr. Erskine is then immediately assassinated by an agent of Nazi Germany"s secret HYDRA research department (headed by Johann Schmidt, a.k.a. the Red Skull), Rogers is left as a unique man who is initially misused as a propaganda mascot'),
(28, 'Real Steel', 2011, 'USA', 'Acción, Drama, Ciencia Ficción, Deportes', '433035', '7,1  (228906 votos)', 'In the near future when people become uninterested in boxing and similar sports, a new sport is created - Robot boxing wherein robots battle each other while being controlled by someone. Charlie Kenton, a former boxer who"s trying to make it in the new sport, not only doesn"t do well, he is very deeply in the red. When he learns that his ex, mother of his son Max, dies, he goes to figure out what to do with him. His ex"s sister wants to take him in but Charlie has first say in the matter. Charlie asks her husband for money so he can buy a new Robot in exchange for turning Max over to them. He takes Max for the summer. And Max improves his control of his robot. But when the robot is destroyed, they go to a scrap yard to get parts. Max finds an old generation robot named Atom and restores him. Max wants Atom to fight but Charlie tells him he won"t last a round. However, Atom wins. And it isn"t long before Atom is getting major bouts. Max gets Charlie to teach Atom how to fight, and the ...'),
(29, 'Cowboys & Aliens', 2011, 'USA', 'Acción, Ciencia Ficción, Suspenso, del Oeste', '409847', '6,1  (156223 votos)', 'The Old West.. where a lone cowboy leads an uprising against a terror from beyond our world. 1873. New Mexico Territory. A stranger with no memory of his past stumbles into the hard desert town of Absolution. The only hint to his history is a mysterious shackle that encircles one wrist. What he discovers is that the people of Absolution don"t welcome strangers, and nobody makes a move on its streets unless ordered to do so by the iron-fisted Colonel Dolarhyde (Ford). It"s a town that lives in fear. But Absolution is about to experience fear it can scarcely comprehend as the desolate city is attacked by marauders from the sky. Screaming down with breathtaking velocity and blinding lights to abduct the helpless one by one, these monsters challenge everything the residents have ever known. Now, the stranger they rejected is their only hope for salvation. As this gunslinger slowly starts to remember who he is and where he"s been, he realizes he holds a secret that could give the town a ...'),
(30, 'Die Hard 2', 1990, 'USA', 'Acción, Suspenso', '99423', '7,1  (239081 votos)', 'After the terrifying events in LA, John McClane (Willis) is about to go through it all again. A team of terrorists, led by Col. Stuart (Sadler) is holding the entire airport hostage. The terrorists are planning to rescue a drug lord from justice. In order to do so, they have seized control of all electrical equipment affecting all planes. With no runway lights available, all aircraft have to remain in the air, with fuel running low, McClane will need to be fast.'),
(31, 'Die Hard', 1988, 'USA', 'Acción, Suspenso', '95016', '8,3  (513688 votos)', 'New York City Detective John McClane has just arrived in Los Angeles to spend Christmas with his wife, but when a group of terrorists, led by Hans Gruber, holds her and everyone in the Nakatomi Plaza building hostage, it"s up to McClane to stop them.'),
(32, 'Divergent', 2014, 'USA', 'Suspenso, Ciencia Ficción, Aventuras', '1840309', '6,8  (264659 votos)', 'Set in a futuristic dystopia where society is divided into five factions that each represent a different virtue, teenagers have to decide if they want to stay in their faction or switch to another - for the rest of their lives. Tris Prior makes a choice that surprises everyone. Then Tris and her fellow faction-members have to live through a highly competitive initiation process to live out the choice they have made. They must undergo extreme physical and intense psychological tests, that transform them all. But Tris has a secret that she is Divergent, which means she doesn"t fit into any one group. If anyone knew, it would mean a certain death. As she discovers a growing conflict that threatens to unravel her seemingly peaceful society, this secret might help her save the people she loves... or it might destroy her.'),
(33, 'Django Unchained', 2012, 'USA', 'del Oeste', '1853728', '8,5  (769570 votos)', 'Former dentist, Dr. King Schultz, buys the freedom of a slave, Django, and trains him with the intent to make him his deputy bounty hunter. Instead, he is led to the site of Django"s wife who is under the hands of Calvin Candie, a ruthless plantation owner.'),
(37, 'Dracula Untold', 2014, 'USA', 'Acción, Terror, Drama, Bélica, Fantasía', '829150', '6,3  (106781 votos)', 'At the turn of the century, the young lord Vlad and his family live a peaceful life ruling over their small kingdom, but when a Turk warlord demands from Vlad a thousand boys and his son to create an army Vlad seeks a terrible power that will allow him to protect his kingdom and family from the Turks at a terrible cost.'),
(38, 'Edge of Tomorrow', 2014, 'USA', 'Acción, Ciencia Ficción', '1631867', '7,9  (324508 votos)', 'An alien race has hit the Earth in an unrelenting assault, unbeatable by any military unit in the world. Major William Cage (Cruise) is an officer who has never seen a day of combat when he is unceremoniously dropped into what amounts to a suicide mission. Killed within minutes, Cage now finds himself inexplicably thrown into a time loop-forcing him to live out the same brutal combat over and over, fighting and dying again...and again. But with each battle, Cage becomes able to engage the adversaries with increasing skill, alongside Special Forces warrior Rita Vrataski (Blunt). And, as Cage and Vrataski take the fight to the aliens, each repeated encounter gets them one step closer to defeating the enemy!'),
(39, 'Concursante', 2007, 'Spain', 'Comedia, Drama', '447907', '6,6  (1078 votos)', 'The Contestant recounts the roller coaster ride of Martin Circo, the lucky winner of the most lucrative game-show prize in television history to the tune of 3 Million Euros. In this biting satire on consumer society, Martin"s stroke of luck sees his life turned upside down. Sometimes, one piece of good luck can ruin your life.'),
(40, 'Maze Runner, The', 2014, 'USA', 'Acción, Suspenso, Ciencia Ficción, Misterio', '1790864', '6,9  (210836 votos)', 'Thomas wakes up in an elevator, remembering nothing but his own name. He emerges into a world of about 60 teen boys who have learned to survive in a completely enclosed environment, subsisting on their own agriculture and supplies. A new boy arrives every 30 days. The original group has been in "The Glade" for three years, trying to find a way to escape through the Maze that surrounds their living space. They have begun to give up hope. Then a comatose girl arrives with a strange note, and their world begins to change. There are some great, fast-paced action scenes, particularly those involving the nightmarish Grievers who plague the boys.'),
(41, 'Jupiter Ascending', 2015, 'USA', 'Acción, Ciencia Ficción, Aventuras', '1617661', '5,6  (67328 votos)', 'Jupiter Jones was born under a night sky, with signs predicting that she was destined for great things. Now grown, Jupiter dreams of the stars but wakes up to the cold reality of a job cleaning other people"s houses and an endless run of bad breaks. Only when Caine Wise, a genetically engineered ex-military hunter, arrives on Earth to track her down does Jupiter begin to glimpse the fate that has been waiting for her all along - her genetic signature marks her as next in line for an extraordinary inheritance that could alter the balance of the cosmos.'),
(42, 'Man Who Shot Liberty Valance, The', 1962, 'USA', 'Drama, del Oeste', '56217', '8,1  (48062 votos)', 'When Senator Ransom Stoddard returns home to Shinbone for the funeral of Tom Doniphon, he recounts to a local newspaper editor the story behind it all. He had come to town many years before, a lawyer by profession. The stage was robbed on its way in by the local ruffian, Liberty Valance, and Stoddard has nothing to his name left save a few law books. He gets a job in the kitchen at the Ericson"s restaurant and there meets his future wife, Hallie. The territory is vying for Statehood and Stoddard is selected as a representative over Valance, who continues terrorizing the town. When he destroys the local newspaper office and attacks the editor, Stoddard calls him out, though the conclusion is not quite as straightforward as legend would have it.'),
(43, 'Rise of the Planet of the Apes', 2011, 'USA', 'Acción, Drama, Ciencia Ficción, Suspenso', '1318514', '7,6  (356088 votos)', 'At the story"s heart is Caesar (Andy Serkis), a chimpanzee who gains human-like intelligence and emotions from an experimental drug. Raised like a child by the drug"s creator, Will Rodman (James Franco) and a primatologist Caroline Aranha (Freida Pinto), Caesar ultimately finds himself taken from the humans he loves and imprisoned in an ape sanctuary in San Bruno. Seeking justice for his fellow inmates, Caesar gives the fellow apes the same drug that he inherited. He then assembles a simian army and escapes the sanctuary - putting man and ape on a collision course that could change the planet forever.'),
(44, 'Seventh Son', 2014, 'USA', 'Acción, Aventuras, Fantasía', '1121096', '5,5  (28589 votos)', 'John Gregory, who is a seventh son of a seventh son and also the local spook, has protected his country from witches, boggarts, ghouls and all manner of things that go bump in the night. However John is not young anymore, and has been seeking an apprentice to carry on his trade. Most have failed to survive. The last hope is a young farmer"s son named Thomas Ward. Will he survive the training to become the spook that so many others couldn"t? Should he trust the girl with pointy shoes? How can Thomas stand a chance against Mother Malkin, the most dangerous witch in the county?'),
(45, 'Priest', 2011, 'USA', 'Acción, Fantasía, Terror, Ciencia Ficción, Suspenso', '822847', '5,7  (89225 votos)', 'PRIEST, a post-apocalyptic sci-fi thriller, is set in an alternate world -- one ravaged by centuries of war between man and vampires. The story revolves around a legendary Warrior Priest from the last Vampire War who now lives in obscurity among the other downtrodden human inhabitants in walled-in dystopian cities ruled by the Church. When his niece is abducted by a murderous pack of vampires, Priest breaks his sacred vows to venture out on a quest to find her before they turn her into one of them. He is joined on his crusade by his niece"s boyfriend, a trigger-fingered young wasteland sheriff, and a former Warrior Priestess who possesses otherworldly fighting skills.'),
(46, 'Last Boy Scout, The', 1991, 'USA', 'Acción, Suspenso, Comedia, Policíaca, Misterio', '102266', '6,9  (69262 votos)', 'A down and out cynical detective teams up with a down and out ex-quarterback to try and solve a murder case involving a pro football team and a politician.'),
(47, 'Elysium', 2013, 'USA', 'Acción, Drama, Ciencia Ficción, Suspenso', '1535108', '6,7  (281640 votos)', 'In the year 2154, two classes of people exist: the very wealthy, who live on a pristine man-made space station called Elysium, and the rest, who live on an overpopulated, ruined Earth. Secretary Delacourt, a government official, will stop at nothing to enforce anti-immigration laws and preserve the luxurious lifestyle of the citizens of Elysium. That doesn"t stop the people of Earth from trying to get in by any means they can. When unlucky Max is backed into a corner, he agrees to take on a daunting mission that, if successful, will not only save his life but could bring equality to these polarized worlds.'),
(49, 'Ender"s Game', 2013, 'USA', 'Acción, Ciencia Ficción', '1731141', '6,7  (160974 votos)', 'The Earth was ravaged by the Formics, an alien race seemingly determined to destroy humanity. Seventy years later, the people of Earth remain banded together to prevent their own annihilation from this technologically superior alien species. Ender Wiggin, a quiet but brilliant boy, may become the savior of the human race. He is separated from his beloved sister and his terrifying brother and brought to battle school in orbit around earth. He will be tested and honed into an empathetic killer who begins to despise what he does as he learns to fight in hopes of saving Earth and his family.'),
(51, 'Epic', 2013, 'USA', 'Animación, Aventuras, Familiar, Fantasía', '848537', '6,7  (76067 votos)', 'Young Mary Katherine (M.K.) returns to her eccentric scientist father"s home, but his all-consuming quest to discover a tiny civilization in the neighboring forest drives them apart. However, M.K. soon finds herself shrunken down by Queen Tara of that forest who was mortally wounded by the putrefying Boggans, and charged to deliver a pod bearing the new Queen to safety. Together with a veteran Leafman warrior, two goofy mollusks and a young maverick, M.K. agrees to help. As the villainous Boggan leader, Mandrake closes in, M.K. and her new friends must draw on the best of themselves together and discover what they have to save their world.'),
(52, 'Lord of the Rings: The Two Towers, The', 2002, 'USA', 'Aventuras, Fantasía', '167261', '8,7  (935917 votos)', 'While Frodo and Sam, now accompanied by a new guide, continue their hopeless journey towards the land of shadow to destroy the One Ring, each member of the broken fellowship plays their part in the battle against the evil wizard Saruman and his armies of Isengard.'),
(53, 'Lord of the Rings: The Return of the King, The', 2003, 'USA', 'Aventuras, Fantasía', '167260', '8,9  (1039179 votos)', 'While Frodo & Sam continue to approach Mount Doom to destroy the One Ring, unaware of the path Gollum is leading them, the former Fellowship aid Rohan & Gondor in a great battle in the Pelennor Fields, Minas Tirith and the Black Gates as Sauron wages his last war against Middle-Earth.'),
(54, 'Exodus: Gods and Kings', 2014, 'UK', 'Acción, Drama, Aventuras', '1528100', '6,1  (87466 votos)', 'Epic adventure Exodus: Gods and Kings is the story of one man"s daring courage to take on the might of an empire. Using state of the art visual effects and 3D immersion, Scott brings new life to the story of the defiant leader Moses as he rises up against the Egyptian Pharaoh Ramses, setting 600,000 slaves on a monumental journey of escape from Egypt and its terrifying cycle of deadly plagues.'),
(56, 'Frozen', 2013, 'USA', 'Animación, Aventuras, Comedia, Familiar, Fantasía, Musical', '2294629', '7,7  (341346 votos)', 'Anna, a fearless optimist, sets off on an epic journey - teaming up with rugged mountain man Kristoff and his loyal reindeer Sven - to find her sister Elsa, whose icy powers have trapped the kingdom of Arendelle in eternal winter. Encountering Everest-like conditions, mystical trolls and a hilarious snowman named Olaf, Anna and Kristoff battle the elements in a race to save the kingdom. From the outside Anna"s sister, Elsa looks poised, regal and reserved, but in reality, she lives in fear as she wrestles with a mighty secret-she was born with the power to create ice and snow. It"s a beautiful ability, but also extremely dangerous. Haunted by the moment her magic nearly killed her younger sister Anna, Elsa has isolated herself, spending every waking minute trying to suppress her growing powers. Her mounting emotions trigger the magic, accidentally setting off an eternal winter that she can"t stop. She fears she"s becoming a monster and that no one, not even her sister, can help her.'),
(57, 'Gantz - Temporada 1', 2004, 'Japan', 'Animación, Drama, Fantasía, Terror, Ciencia Ficción, Suspenso', '434685', '7,4  (4333 votos)', 'High school student Kei Kurono meets up with childhood friend Kato Masaru one day by chance encounter. As the two are in the subway chatting, Kato notices a homeless man on the subway train tracks. Kato goes down on to the tracks to move the man off the tracks and persuades Kei to help. But soon after helping the man, they are hit by a subway train and killed... or maybe not. Immediately after being hit by the train, the two are suddenly in an apartment from which they can"t leave, along with some other people who were also in some near death experience. In this apartment there is also a black sphere called Gantz. Kei and the others have to obey Gantz"s rules if they want to live. They have to participate in missions in which the objective is to eliminate aliens. But who or what are these aliens? are Kei, Kato and the others alive or dead?'),
(58, 'Despicable Me 2', 2013, 'USA', 'Animación, Comedia, Familiar', '1690953', '7,5  (233613 votos)', 'While Gru, the ex-supervillain is adjusting to family life and an attempted honest living in the jam business, a secret Arctic laboratory is stolen. The Anti-Villain League decides it needs an insider"s help and recruits Gru in the investigation. Together with the eccentric AVL agent, Lucy Wilde, Gru concludes that his prime suspect is the presumed dead supervillain, El Macho, whose his teenage son is also making the moves on his eldest daughter, Margo. Seemingly blinded by his overprotectiveness of his children and his growing mutual attraction to Lucy, Gru seems on the wrong track even as his minions are being quietly kidnapped en masse for some malevolent purpose.'),
(59, 'Despicable Me 2', 2013, 'USA', 'Comedia, Animación, Familiar', '1690953', '7,5  (233705 votos)', 'While Gru, the ex-supervillain is adjusting to family life and an attempted honest living in the jam business, a secret Arctic laboratory is stolen. The Anti-Villain League decides it needs an insider"s help and recruits Gru in the investigation. Together with the eccentric AVL agent, Lucy Wilde, Gru concludes that his prime suspect is the presumed dead supervillain, El Macho, whose his teenage son is also making the moves on his eldest daughter, Margo. Seemingly blinded by his overprotectiveness of his children and his growing mutual attraction to Lucy, Gru seems on the wrong track even as his minions are being quietly kidnapped en masse for some malevolent purpose.'),
(60, 'Guardians of the Galaxy', 2014, 'USA', 'Acción, Ciencia Ficción, Aventuras', '2015381', '8,1  (479298 votos)', 'After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the "Guardians of the Galaxy" to save the world.'),
(61, 'Hansel y Gretel: Cazadores de brujas', 2013, 'Germany', 'Acción, Fantasía, Terror', '1428538', '6,1  (141147 votos)', 'The siblings Hansel and Gretel are left alone in the woods by their father and captured by a dark witch in a candy house. However they kill the witch and escape from the spot. Years later, the orphans have become famous witch hunters. When eleven children go missing in a small village, the Mayor summons Hansel and Gretel to rescue them, and they save the red haired Mina from the local sheriff that wants to burn her accusing Mina of witchcraft. Soon they discover that the Blood Moon will approach in three days and the powerful dark witch Muriel is the responsible for the abduction of children. She intends to use the children together with a secret ingredient in a Sabbath to make the coven of witches protected against the fire. Meanwhile Hansel and Gretel disclose secrets about their parents.'),
(62, 'Inception', 2010, 'USA', 'Acción, Misterio, Ciencia Ficción, Suspenso', '1375666', '8,8  (1220669 votos)', 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb"s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible-inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.'),
(63, 'Interstellar', 2014, 'USA', 'Ciencia Ficción, Aventuras', '816692', '8,7  (615560 votos)', 'In the near future, Earth has been devastated by drought and famine, causing a scarcity in food and extreme changes in climate. When humanity is facing extinction, a mysterious rip in the space-time continuum is discovered, giving mankind the opportunity to widen its lifespan. A group of explorers must travel beyond our solar system in search of a planet that can sustain life. The crew of the Endurance are required to think bigger and go further than any human in history as they embark on an interstellar voyage into the unknown. Coop, the pilot of the Endurance, must decide between seeing his children again and the future of the human race.'),
(64, 'In Time', 2011, 'USA', 'Acción, Suspenso, Ciencia Ficción', '1637688', '6,7  (265239 votos)', 'Welcome to a world where time has become the ultimate currency. You stop aging at 25, but there"s a catch: you"re genetically-engineered to live only one more year, unless you can buy your way out of it. The rich "earn" decades at a time (remaining at age 25), becoming essentially immortal, while the rest beg, borrow or steal enough hours to make it through the day. When a man from the wrong side of the tracks is falsely accused of murder, he is forced to go on the run with a beautiful hostage. Living minute to minute, the duo"s love becomes a powerful tool in their war against the system.'),
(65, 'Wrath of the Titans', 2012, 'USA', 'Acción, Aventuras, Fantasía', '1646987', '5,8  (138046 votos)', 'A decade after his heroic defeat of the monstrous Kraken, Perseus-the demigod son of Zeus-is attempting to live a quieter life as a village fisherman and the sole parent to his 10-year old son, Helius. Meanwhile, a struggle for supremacy rages between the gods and the Titans. Dangerously weakened by humanity"s lack of devotion, the gods are losing control of the imprisoned Titans and their ferocious leader, Kronos, father of the long-ruling brothers Zeus, Hades and Poseidon. The triumvirate had overthrown their powerful father long ago, leaving him to rot in the gloomy abyss of Tartarus, a dungeon that lies deep within the cavernous underworld. Perseus cannot ignore his true calling when Hades, along with Zeus" godly son, Ares (Edgar Ramírez), switch loyalty and make a deal with Kronos to capture Zeus. The Titans" strength grows stronger as Zeus" remaining godly powers are siphoned, and hell is unleashed on earth. Enlisting the help of the warrior Queen Andromeda (Rosamund Pike), ...'),
(67, 'John Wick', 2014, 'USA', 'Acción, Suspenso', '2911666', '7,2  (157153 votos)', 'John Wick is a mob hit man who, upon falling in love, quits. 5 years later, his wife dies and to make sure he"s not alone she arranges for a dog to be brought to him after her death. Later, some men wanting his car break in and beat him up and kill his dog. When he recovers, he sets to get the ones who killed his dog. He learns that the leader is the son of his former employer. And the man wanting to protect his son, tries to take care of Wick but he"s still as good as he was.'),
(69, 'John Carter', 2012, 'USA', 'Acción, Ciencia Ficción, Aventuras, Fantasía', '401729', '6,6  (192159 votos)', 'John Carter, a Civil War veteran, who in 1868 was trying to live a normal life, is "asked" by the Army to join, but he refuses so he is locked up. He escapes, and is pursued. Eventually they run into some Indians, and there"s a gunfight. Carter seeks refuge in a cave. While there, he encounters someone who is holding some kind of medallion. When Carter touches it, he finds himself in a place where he can leap incredible heights, among other things. He later encounters beings he has never seen before. He meets a woman who helps him to discover that he is on Mars, and he learns there"s some kind of unrest going on.'),
(70, 'Kill Bill: Vol. 1', 2003, 'USA', 'Acción', '266697', '8,1  (624394 votos)', 'The lead character, called "The Bride," was a member of the Deadly Viper Assassination Squad, led by her lover "Bill." Upon realizing she was pregnant with Bill"s child, "The Bride" decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, "The Bride" wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.'),
(71, 'Kill Bill: Vol. 2', 2004, 'USA', 'Acción, Policíaca, Suspenso', '378194', '8,0  (447266 votos)', 'The murderous Bride is back and she is still continuing her vengeance quest against her ex-boss, Bill, and taking aim at Bill"s younger brother Budd and Elle Driver, the only survivors from the squad of assassins who betrayed her four years earlier. It"s all leading up to the ultimate confrontation with Bill, the Bride"s former master and the man who ordered her execution!'),
(72, 'La isla mínima', 2014, 'Spain', 'Suspenso, Policíaca', '3253930', '7,4  (6830 votos)', 'The Spanish deep South, 1980. A series of brutal murders of adolescent girls in a remote and forgotten town bring together two disparate characters - both detectives in the homicide division - to investigate the cases. With deep divisions in their ideology, detectives Juan and Pedro must put aside their differences if they are to successfully hunt down a killer who for years has terrorized a community in the shadow of a general disregard for women rooted in a misogynistic past.'),
(73, 'Lego Movie, The', 2014, 'Australia', 'Comedia, Aventuras, Fantasía, Animación, Familiar', '1490017', '7,8  (204695 votos)', 'The LEGO Movie is a 3D animated film which follows lead character, Emmet a completely ordinary LEGO mini-figure who is identified as the most "extraordinary person" and the key to saving the Lego universe. Emmet and his friends go on an epic journey to stop the evil tyrant, Lord Business.'),
(74, 'Lego DC Comics Super Heroes: Justice League vs. Bizarro League', 2015, 'USA', 'Acción, Comedia, Aventuras, Animación', '4189260', '5,8  (409 votos)', 'Wherever there is chaos and destruction, you will find Superman"s mixed-up clone, Bizarro, who hears the opposite of what is said, says the opposite of what he means and does the opposite of what is right. The Man of Steel decides it"s time to find a new home for him...on another planet, Bizarro World! On Earth, Superman and the Justice League go about the usual business of stopping bad guys. But when Bizarro World is threatened with destruction by the galactic tyrant, Darkseid, Bizarro returns to Earth and clones the Justice League to create more "heroes" like himself'),
(75, 'Signal, The', 2014, 'USA', 'Suspenso, Ciencia Ficción', '2910814', '6,1  (34889 votos)', 'On a road trip, Nic and two friends are drawn to an isolated area by a computer genius. When everything suddenly goes dark, Nic regains consciousness - only to find himself in a waking nightmare.'),
(76, 'Las aventuras de Tadeo Jones', 2012, 'Spain', 'Animación, Aventuras, Comedia, Familiar', '1764625', '5,9  (4700 votos)', 'Tad is a celebrity archeologist and adventurer just like his hero Max Mordon... in his dreams! In reality, Tad is a Chicago construction worker. One day, however, he is mistaken for a real Professor and takes his place on a flight to Peru in search of the Lost City of Paititi. Professor Lavrof and his beautiful daughter Sara are waiting for the famous professor to crack the code. Unfortunately for Tad, Sara is engaged to real-life hero Max Mordon, but Max has secretly betrayed the Professor by teaming up with the evil Kopponen and his shady Odysseus corporation. Time for Tad to step up.'),
(77, 'Teenage Mutant Ninja Turtles', 2014, 'USA', 'Acción, Ciencia Ficción, Comedia, Aventuras, Fantasía', '1291150', '6,0  (129695 votos)', 'Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April O"Neil and her cameraman Vern Fenwick to save the city and unravel Shredder"s diabolical plan.'),
(79, 'Lions for Lambs', 2007, 'USA', 'Drama, Suspenso, Bélica', '891527', '6,2  (38867 votos)', 'Three stories told simultaneous in ninety minutes of real time: a Republican Senator who"s a presidential hopeful gives an hour-long interview to a skeptical television reporter, detailing a strategy for victory in Afghanistan'),
(80, 'Licence to Kill', 1989, 'UK', 'Acción, Aventuras, Suspenso', '97742', '6,6  (65087 votos)', 'James Bond is on possibly his most brutal mission yet. Bond"s good friend, Felix Leiter, is left near death, by drug baron Franz Sanchez. Bond sets off on the hunt for Sanchez, but not everyone is happy. MI6 does not feel Sanchez is their problem and strips Bond of his license to kill making Bond more dangerous than ever. Bond gains the aid of one of Leiter"s friends, known as Pam Bouvier and sneaks his way into the drug factories, which Sanchez owns. Will Bond be able to keep his identity secret, or will Sanchez see Bond"s true intentions?'),
(81, 'Cloudy with a Chance of Meatballs 2', 2013, 'USA', 'Ciencia Ficción, Comedia, Fantasía, Animación, Familiar', '1985966', '6,5  (51863 votos)', 'After the disastrous food storm in the first film, Flint and his friends are forced to leave the town. Flint accepts the invitation from his idol Chester V to join The Live Corp Company, which has been tasked to clean the island, and where the best inventors in the world create technologies for the betterment of mankind. When Flint discovers that his machine still operates and now creates mutant food beasts like living pickles, hungry tacodiles, shrimpanzees and apple pie-thons, he and his friends must return to save the world.'),
(82, 'Looper', 2012, 'USA', 'Acción, Suspenso, Ciencia Ficción, Policíaca', '1276104', '7,5  (375132 votos)', 'In the year 2044, a man working for a group of killers called "Loopers" (they work for the mob and kill people who are sent blindfolded back in time from the year 2074 by their bosses) recognizes a victim as himself. He hesitates resulting in the escape of his older self.'),
(84, 'Internship, The', 2013, 'USA', 'Comedia', '2234155', '6,3  (140511 votos)', 'Billy (Vince Vaughn) and Nick (Owen Wilson) are salesmen whose careers have been torpedoed by the digital world. Trying to prove they are not obsolete, they defy the odds by talking their way into a coveted internship at Google, along with a battalion of brilliant college students. But, gaining entrance to this utopia is only half the battle. Now they must compete with a group of the nation"s most elite, tech-savvy geniuses to prove that necessity really is the mother of re-invention.'),
(85, 'Boxtrolls, The', 2014, 'USA', 'Comedia, Aventuras, Fantasía, Animación, Familiar', '787474', '6,8  (28685 votos)', 'THE BOXTROLLS are a community of quirky, mischievous creatures who have lovingly raised an orphaned human boy named Eggs in the amazing cavernous home they"ve built beneath the streets of a city called Cheesebridge. The story is about a young orphaned boy raised by underground cave-dwelling trash collectors who tries to save his friends from an evil exterminator, the town"s villain, Archibald Snatcher. When Snatcher comes up with a plot to get rid of the Boxtrolls. Eggs decides to venture above ground and "into the light," where he meets and teams up with fabulously feisty Winnie. Together, they devise a daring plan to save The BoxTrolls family. The film is based upon the children"s novel "Here Be Monsters" by Alan Snow.'),
(86, 'Penguins of Madagascar', 2014, 'USA', 'Comedia, Aventuras, Animación, Familiar', '1911658', '6,8  (39960 votos)', 'Super spy teams aren"t born...they"re hatched. Discover the secrets of the greatest and most hilarious covert birds in the global espionage biz: Skipper, Kowalski, Rico and Private. These elitists of the elite are joining forces with a chic undercover organization, The North Wind. Led by handsome and husky Agent Classified (we could tell you his name, but then...you know). Together, they must stop the villainous Dr. Octavius Brine, from destroying the world as we know it.'),
(87, 'Surrogates', 2009, 'USA', 'Acción, Ciencia Ficción, Suspenso', '986263', '6,3  (142538 votos)', 'People are living their lives remotely from the safety of their own homes via robotic surrogates -- sexy, physically perfect mechanical representations of themselves. It"s an ideal world where crime, pain, fear and consequences don"t exist. When the first murder in years jolts this utopia, FBI agent Greer discovers a vast conspiracy behind the surrogate phenomenon and must abandon his own surrogate, risking his life to unravel the mystery.'),
(88, 'Red Lights', 2012, 'Spain', 'Drama, Misterio, Suspenso', '1748179', '6,2  (43935 votos)', 'The skeptical psychologist Dr. Margaret Matheson and her assistant, physicist Tom Buckley, are specialists in disclosing fraudulent paranormal phenomena. When the famous psychic Simon Silver reappears to his public after many years of absence, Tom becomes singularly obsessed in determining whether Silver is a fraud or not.'),
(89, 'Maleficent', 2014, 'USA', 'Acción, Aventuras, Fantasía, Familiar, Romántica', '1587310', '7,1  (205456 votos)', 'A beautiful, pure-hearted young woman, Maleficent has an idyllic life growing up in a peaceable forest kingdom, until one day when an invading army threatens the harmony of the land. Maleficent rises to be the land"s fiercest protector, but she ultimately suffers a ruthless betrayal - an act that begins to turn her pure heart to stone. Bent on revenge, Maleficent faces a battle with the invading king"s successor and, as a result, places a curse upon his newborn infant Aurora. As the child grows, Maleficent realizes that Aurora holds the key to peace in the kingdom - and perhaps to Maleficent"s true happiness as well.'),
(90, 'Men in Black II', 2002, 'USA', 'Acción, Comedia, Fantasía, Ciencia Ficción', '120912', '6,0  (231228 votos)', 'Kay and Jay reunite to provide our best, last and only line of defense against a sinister seductress who levels the toughest challenge yet to the MIBs untarnished mission statement: protecting the earth from the scum of the universe. It"s been four years since the alien-seeking agents averted an intergalactic disaster of epic proportions. And now it"s a race against the clock as Jay must convince Kay-who not only has absolutely no memory of his time spent with the Men In Black, but is also the only living person left with the expertise to save the galaxy-to reunite with the MIB before the earth submits to ultimate destruction.');
INSERT INTO `peliculas` (`id_pelicula`, `titulo`, `año`, `pais`, `genero`, `imdb`, `clasificacion_imdb`, `resumen`) VALUES
(91, 'Men in Black', 1997, 'USA', 'Comedia, Ciencia Ficción', '119654', '7,2  (350514 votos)', 'Based off of the comic book. Unbeknownst to other people, there is a private agency code named MiB. This agency is some kind of extra terrestrial surveillance corporation. Then, one of the agency"s finest men only going by the name "K", is recruiting for a new addition to the agency. He has chosen James Edwards of the N.Y.P.D. Then, one day, a flying saucer crashes into Earth. This was an alien a part of the "Bug" race. He takes the body of a farmer and heads to New York. He is searching for a super energy source called "The Galaxy". Now, Agents J and K must stop the bug before it can escape with the galaxy.'),
(92, 'Men in Black 3', 2012, 'USA', 'Acción, Ciencia Ficción, Comedia', '1409024', '6,9  (232254 votos)', 'After breaking out of a moon-based maximum security prison, Boris the Animal decides to go back in time and eliminate the person who arrested him - Agent K. When he does so, Agent J realizes that the time line has been changed and he too travels back to July 15, 1969, the day before Agent K is killed. After overcoming some disbelief, J manages to convince K and others of just who he is and why he"s there. With the help of a being who can see all time lines, they track Boris down. J also learns a secret, something K had never told him.'),
(93, 'Mission: Impossible - Ghost Protocol', 2011, 'USA', 'Acción, Aventuras, Suspenso', '1229238', '7,4  (314667 votos)', 'In the fourth installment of the Mission Impossible series, Ethan Hunt and a new team race against time to track down Hendricks, a dangerous terrorist who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt by the team to stop him at the Kremlin ends in a disaster, with an explosion causing severe damage to the Kremlin and the IMF being implicated in the bombing, forcing the President to invoke Ghost Protocol, under which the IMF is disavowed, and will be offered no help or backup in any form. Undaunted, Ethan and his team chase Hendricks to Dubai, and from there to Mumbai, but several spectacular action sequences later, they might still be too late to stop a disaster.'),
(94, 'Monsters University', 2013, 'USA', 'Animación, Aventuras, Comedia, Familiar, Fantasía', '1453405', '7,4  (191333 votos)', 'Mike Wazowski and James P. Sullivan are an inseparable pair, but that wasn"t always the case. From the moment these two mismatched monsters met they couldn"t stand each other. "Monsters University" unlocks the door to how Mike and Sulley overcame their differences and became the best of friends.'),
(95, 'Nightcrawler', 2014, 'USA', 'Policíaca, Suspenso', '2872718', '7,9  (186976 votos)', 'NIGHTCRAWLER is a thriller set in the nocturnal underbelly of contemporary Los Angeles. Jake Gyllenhaal stars as Lou Bloom, a driven young man desperate for work who discovers the high-speed world of L.A. crime journalism. Finding a group of freelance camera crews who film crashes, fires, murder and other mayhem, Lou muscles into the cut-throat, dangerous realm of nightcrawling - where each police siren wail equals a possible windfall and victims are converted into dollars and cents. Aided by Rene Russo as Nina, a veteran of the blood-sport that is local TV news, Lou blurs the line between observer and participant to become the star of his own story.'),
(96, 'No Country for Old Men', 2007, 'USA', 'Policíaca, Drama, Suspenso', '477348', '8,1  (524083 votos)', 'In rural Texas, welder and hunter Llewelyn Moss discovers the remains of several drug runners who have all killed each other in an exchange gone violently wrong. Rather than report the discovery to the police, Moss decides to simply take the two million dollars present for himself. This puts the psychopathic killer, Anton Chigurh, on his trail as he dispassionately murders nearly every rival, bystander and even employer in his pursuit of his quarry and the money. As Moss desperately attempts to keep one step ahead, the blood from this hunt begins to flow behind him with relentlessly growing intensity as Chigurh closes in. Meanwhile, the laconic Sherrif Ed Tom Bell blithely oversees the investigation even as he struggles to face the sheer enormity of the crimes he is attempting to thwart.'),
(97, 'Ocho apellidos vascos', 2014, 'Spain', 'Comedia', '2955316', '6,6  (7960 votos)', 'Rafael, a Seville citizen who has never left the Spanish region of Andalucia, decides to leave his homeland to follow Amaia, a Basque girl unlike other women he has known.'),
(98, 'Outlander', 2008, 'USA', 'Acción, Aventuras, Ciencia Ficción', '462465', '6,3  (60396 votos)', 'In 709 AD, in the Iron Age, a spacecraft crashes in the Viking kingdom of Herot, Norway, and the pilot Kainan survives. He turns the beacon on'),
(99, 'Pacific Rim', 2013, 'USA', 'Acción, Aventuras, Ciencia Ficción', '1663662', '7,0  (325986 votos)', 'When monstrous creatures, known as Kaiju, started rising from the sea, a war began that would take millions of lives and consume humanity"s resources for years on end. To combat the giant Kaiju, a special type of weapon was devised: massive robots, called Jaegers, which are controlled simultaneously by two pilots whose minds are locked in a neural bridge. But even the Jaegers are proving nearly defenseless in the face of the relentless Kaiju. On the verge of defeat, the forces defending mankind have no choice but to turn to two unlikely heroes - a washed up former pilot (Charlie Hunnam) and an untested trainee (Rinko Kikuchi) - who are teamed to drive a legendary but seemingly obsolete Jaeger from the past. Together, they stand as mankind"s last hope against the mounting apocalypse.'),
(102, 'Predators', 2010, 'USA', 'Acción, Aventuras, Ciencia Ficción, Suspenso', '1424381', '6,4  (156674 votos)', 'The mercenary Royce'),
(103, 'R.I.P.D.', 2013, 'USA', 'Acción, Ciencia Ficción, Comedia', '790736', '5,6  (79359 votos)', 'After Nick is murdered by his own partner, he joins the Rest in Peace Department to protect the world from the undeads. While working with his new partner, many undeads are seen gathering in Boston. Soon he realizes that someone close to him is behind all a plot to bring on the apocalypse.'),
(104, 'Red Planet', 2000, 'USA', 'Acción, Ciencia Ficción, Suspenso', '199753', '5,6  (44229 votos)', 'In the near future, Earth is dying. A new colony on Mars could be humanity"s only hope. A team of American astronauts, each a specialist in a different field, is making the first manned expedition to the red planet and must struggle to overcome the differences in their personalities, backgrounds and ideologies for the overall good of the mission. When their equipment suffers life-threatening damage and the crew must depend on one another for survival on the hostile surface of Mars, their doubts, fears and questions about God, man"s destiny and the nature of the universe become defining elements in their fates. In this alien environment they must come face to face with their most human selves.'),
(105, 'Back to the Future', 1985, 'USA', 'Aventuras, Comedia, Romántica, Ciencia Ficción', '88763', '8,5  (600572 votos)', 'Marty McFly, a typical American teenager of the Eighties, is accidentally sent back to 1955 in a plutonium-powered DeLorean "time machine" invented by slightly mad scientist. During his often hysterical, always amazing trip back in time, Marty must make certain his teenage parents-to-be meet and fall in love - so he can get back to the future.'),
(106, 'Riddick', 2013, 'USA', 'Acción, Suspenso, Ciencia Ficción', '1411250', '6,4  (108866 votos)', 'The infamous Riddick has been left for dead on a sun-scorched planet that appears to be lifeless. Soon, however, he finds himself fighting for survival against alien predators more lethal than any human he"s encountered. The only way off is for Riddick to activate an emergency beacon and alert mercenaries who rapidly descend to the planet in search of their bounty. The first ship to arrive carries a new breed of merc, more lethal and violent, while the second is captained by a man whose pursuit of Riddick is more personal. With time running out and a storm on the horizon that no one could survive, his hunters won"t leave the planet without Riddick"s head as their trophy.'),
(107, 'Scarface', 1983, 'USA', 'Drama, Policíaca', '86250', '8,3  (460219 votos)', 'Tony Montana manages to leave Cuba during the Mariel exodus of 1980. He finds himself in a Florida refugee camp but his friend Manny has a way out for them: undertake a contract killing and arrangements will be made to get a green card. He"s soon working for drug dealer Frank Lopez and shows his mettle when a deal with Columbian drug dealers goes bad. He also brings a new level of violence to Miami. Tony is protective of his younger sister but his mother knows what he does for a living and disowns him. Tony is impatient and wants it all however, including Frank"s empire and his mistress Elvira Hancock. Once at the top however, Tony"s outrageous actions make him a target and everything comes crumbling down.'),
(108, 'Faster', 2010, 'USA', 'Acción, Suspenso, Drama, Policíaca', '1433108', '6,5  (74210 votos)', 'A lone man, recently released from prison, seeks out the people from his past who he believes betrayed him. While he forces each to atone for their sins, he must also face what meting out vengeance will do to his immortal soul. Meanwhile, he"s not the only one looking to settle old scores. Hired by the man responsible for the events which lead him to prison, an eccentric contract killer follows his every move. Scenes of them crossing paths, sometimes violently, are interspersed with the assassin"s self-realizations of how to deal with struggles within his own life. As if old enemies & hired guns aren"t enough, a young female detective begrudgingly works alongside a veteran investigator looking to simply survive his last two weeks on the force before retirement, as they seek out the brazen ex-con who has been blazing a path of gasoline-powered destruction in his vintage Chevelle.'),
(109, 'Serenity', 2005, 'USA', 'Acción, Aventuras, Ciencia Ficción, Suspenso', '379786', '8,0  (221413 votos)', 'In the future, a spaceship called Serenity is harboring a passenger with a deadly secret. Six rebels on the run. An assassin in pursuit. When the renegade crew of Serenity agrees to hide a fugitive on their ship, they find themselves in an awesome action-packed battle between the relentless military might of a totalitarian regime who will destroy anything - or anyone - to get the girl back and the bloodthirsty creatures who roam the uncharted areas of space. But, the greatest danger of all may be on their ship.'),
(110, 'Knowing', 2009, 'USA', 'Acción, Suspenso, Drama, Ciencia Ficción, Misterio', '448011', '6,2  (172263 votos)', 'In the fall of 1959, for a time capsule, students draw pictures of life as they imagine it will be in 50 years. Lucinda, an odd child who hears voices, swiftly writes a long string of numbers. In 2009, the capsule is opened'),
(111, 'Solomon Kane', 2009, 'France', 'Acción, Aventuras, Fantasía', '970452', '6,1  (55102 votos)', 'Once a mercenary of Queen Elizabeth I fighting Spaniards in Africa, Solomon met the Devil"s Reaper and discovered he was bound for hell. Barely escaping, he soon renounced violence to atone for his past sins, seeking out redemption in a life of peace. That is until the followers of sorcerer Malachi kidnap a Puritan girl, Meredith Crowthorn, and brutally slaughter her family before his very eyes, forcing Solomon to take up arms and return to his violent ways once more to rescue her.'),
(112, 'I Am Legend', 2007, 'USA', 'Drama, Ciencia Ficción, Suspenso', '480249', '7,2  (457030 votos)', 'Robert Neville is a scientist who was unable to stop the spread of the terrible virus that was incurable and man-made. Immune, Neville is now the last human survivor in what is left of New York City and perhaps the world. For three years, Neville has faithfully sent out daily radio messages, desperate to find any other survivors who might be out there. But he is not alone. Mutant victims of the plague -- The Infected -- lurk in the shadows... watching Neville"s every move... waiting for him to make a fatal mistake. Perhaps mankind"s last, best hope, Neville is driven by only one remaining mission: to find a way to reverse the effects of the virus using his own immune blood. But he knows he is outnumbered... and quickly running out of time.'),
(113, 'Harlock: Space Pirate', 2013, 'Japan', 'Ciencia Ficción, Aventuras, Animación', '2668134', '6,5  (6365 votos)', '2977: For many years a mighty battle has been raging across the galaxies as 500 billion humans, whose forebears were exiled from Earth, plan to return to what is still called home. Forced to flee a ravaged Earth, humans have now depleted the corners of the galaxy to which they fled. Earth has now become the most valued and precious resource of all, controlled by the corrupt Gaia Coalition which governs the human race across the different galaxies. Having been exiled and vilified during the battle of the Homecoming War, Captain Harlock and his trusted crew of the Arcadia battle cruiser are the only hope mankind has of discovering the secrets that the Gaia have kept hidden. The Coalition has demanded Harlock"s death and the Gaia Fleet"s new leader, Ezra, calls on his younger brother, Logan, to infiltrate the Arcadia and then assassinate Harlock, thus forever eradicating the one man standing between the Coalition and their complete control of the Universe. Logan must make a very personal...'),
(115, 'Star Trek', 2009, 'USA', 'Acción, Aventuras, Ciencia Ficción', '796366', '8,0  (459509 votos)', 'On the day of James Kirk"s birth, his father dies on his ship in a last stand against a mysterious alien time-traveling vessel looking for Ambassador Spock, who, in this time, is also a child on Vulcan disdained by his neighbors for his half-human heritage. Twenty-five years later, Kirk has grown into a young troublemaker. Challenged by Captain Christopher Pike to realize his potential in Starfleet, he comes to annoy instructors like young Commander Spock. Suddenly, there is an emergency at Vulcan and the newly commissioned USS Enterprise is crewed with promising cadets like Nyota Uhura, Hikaru Sulu, Pavel Chekov and even Kirk himself, thanks to Leonard McCoy"s medical trickery. Together, this crew will have an adventure in the final frontier where the old legend is altered forever as a new version of it begins.'),
(116, 'Star Trek Into Darkness', 2013, 'USA', 'Acción, Ciencia Ficción, Aventuras', '1408101', '7,8  (347713 votos)', 'When the crew of the Enterprise is called back home, they find an unstoppable force of terror from within their own organization has detonated the fleet and everything it stands for, leaving our world in a state of crisis. With a personal score to settle, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction. As our heroes are propelled into an epic chess game of life and death, love will be challenged, friendships will be torn apart, and sacrifices must be made for the only family Kirk has left: his crew.'),
(118, 'Star Trek Into Darkness', 2013, 'USA', 'Acción, Aventuras, Ciencia Ficción', '1408101', '7,8  (347621 votos)', 'When the crew of the Enterprise is called back home, they find an unstoppable force of terror from within their own organization has detonated the fleet and everything it stands for, leaving our world in a state of crisis. With a personal score to settle, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction. As our heroes are propelled into an epic chess game of life and death, love will be challenged, friendships will be torn apart, and sacrifices must be made for the only family Kirk has left: his crew.'),
(119, 'Dark Knight Rises, The', 2012, 'USA', 'Acción, Suspenso', '1345836', '8,5  (959328 votos)', 'Despite his tarnished reputation after the events of The Dark Knight, in which he took the rap for Dent"s crimes, Batman feels compelled to intervene to assist the city and its police force which is struggling to cope with Bane"s plans to destroy the city.'),
(121, 'Interview, The', 2014, 'USA', 'Acción, Comedia', '2788710', '6,8  (202381 votos)', 'In the action-comedy The Interview, Dave Skylark (James Franco) and his producer Aaron Rapoport (Seth Rogen) run the popular celebrity tabloid TV show "Skylark Tonight." When they discover that North Korean dictator Kim Jong-un is a fan of the show, they land an interview with him in an attempt to legitimize themselves as journalists. As Dave and Aaron prepare to travel to Pyongyang, their plans change when the CIA recruits them, perhaps the two least-qualified men imaginable, to assassinate Kim Jong-un.'),
(122, 'Watch, The', 2012, 'USA', 'Acción, Comedia, Ciencia Ficción', '1298649', '5,7  (93536 votos)', 'In Glenview, Ohio, Evan is the manager of the Costco department store and married to Abby. When the Costco night watchman, Antonio Guzman, is mysteriously murdered, Evan organizes The Neighborhood Watch, a watch team with his suburban neighbors Bob, Franklin and Jamarcus to protect the neighborhood and find the killer of Antonio. Soon they discover that the murderer is an alien that is preparing to invade Earth, and they become the last hope of mankind on Earth.'),
(123, 'Cabin in the Woods, The', 2012, 'USA', 'Suspenso, Terror, Misterio', '1259521', '7,0  (239684 votos)', 'Five teenagers head off for a weekend at a secluded cabin in the woods. They arrive to find they are quite isolated with no means of communicating with the outside world. When the cellar door flings itself open, they of course go down to investigate. They find an odd assortment of relics and curios, but when one of the women, Dana, reads from a book, she awakens a family of deadly zombie killers. However, there"s far more going on than meets the eye, as the five campers are all under observation.'),
(125, 'Dead Zone, The', 1983, 'USA', 'Suspenso, Terror, Ciencia Ficción', '85407', '7,3  (39736 votos)', 'Christopher Walken wakes from a coma due to a car accident, only to find he has lost five years of his life, and yet gained psychic powers. Foreseeing the future appears to be a "gift" at first, but ends up causing problems...'),
(126, 'Expendables 3, The', 2014, 'USA', 'Acción, Suspenso, Aventuras', '2333784', '6,2  (96913 votos)', 'Barney (Stallone), Christmas (Statham) and the rest of the team comes face-to-face with Conrad Stonebanks (Gibson), who years ago co-founded The Expendables with Barney. Stonebanks subsequently became a ruthless arms trader and someone who Barney was forced to kill... or so he thought. Stonebanks, who eluded death once before, now is making it his mission to end The Expendables -- but Barney has other plans. Barney decides that he has to fight old blood with new blood, and brings in a new era of Expendables team members, recruiting individuals who are younger, faster and more tech-savvy. The latest mission becomes a clash of classic old-school style versus high-tech expertise in the Expendables" most personal battle yet.'),
(127, 'Expendables 3, The', 2014, 'USA', 'Acción, Aventuras, Suspenso', '2333784', '6,2  (96840 votos)', 'Barney (Stallone), Christmas (Statham) and the rest of the team comes face-to-face with Conrad Stonebanks (Gibson), who years ago co-founded The Expendables with Barney. Stonebanks subsequently became a ruthless arms trader and someone who Barney was forced to kill... or so he thought. Stonebanks, who eluded death once before, now is making it his mission to end The Expendables -- but Barney has other plans. Barney decides that he has to fight old blood with new blood, and brings in a new era of Expendables team members, recruiting individuals who are younger, faster and more tech-savvy. The latest mission becomes a clash of classic old-school style versus high-tech expertise in the Expendables" most personal battle yet.'),
(129, 'Hobbit: An Unexpected Journey, The', 2012, 'USA', 'Aventuras, Fantasía', '903624', '8,0  (558688 votos)', 'Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild'),
(130, 'Last Days on Mars, The', 2013, 'UK', 'Suspenso, Terror, Ciencia Ficción', '1709143', '5,5  (24481 votos)', 'On the last day of the first manned mission to Mars, a crew member of Tantalus Base believes he has made an astounding discovery - fossilized evidence of bacterial life. Unwilling to let the relief crew claims all the glory, he disobeys orders to pack up and goes out on an unauthorized expedition to collect further samples. But a routine excavation turns to disaster when the porous ground collapses and he falls into a deep crevice and near certain death. His devastated colleagues attempt to recover his body. However, when another vanishes, they start to suspect that the life-form they have discovered is not without danger.'),
(132, 'Thor: The Dark World', 2013, 'USA', 'Acción, Aventuras, Fantasía', '1981115', '7,1  (330717 votos)', 'Thousands of years ago, a race of beings known as Dark Elves tried to send the universe into darkness by using a weapon known as the Aether. Warriors from Asgard stop them but their leader Malekith escapes to wait for another opportunity. The warriors find the Aether and since it cannot be destroyed, they try to hide it. In the present day, Jane Foster awaits the return of Thor although it has been two years since they last saw once another. In the meantime, Thor has been trying to bring peace to the nine realms. Jane discovers an anomaly similar to the one that brought Thor to Earth. She goes to investigate, finds a wormhole, and is sucked into it. Back on Asgard, Thor wishes to return to Earth but his father, Odin refuses to let him. Thor learns from Heimdall, who can see into all of the realms, that Jane disappeared. Thor then returns to Earth just as Jane reappears. However, when some policemen try to arrest her, an unknown energy repulses them. Thor then brings Jane to Asgard to ...'),
(133, 'Time Bandits', 1981, 'UK', 'Aventuras, Comedia, Fantasía, Ciencia Ficción', '81633', '7,0  (41508 votos)', 'A young boy"s wardrobe contains a time hole. Through this hole an assortment of short people (i.e. dwarfs) come while escaping from their master, the supreme being. They take Kevin with them on their adventures through time from Napoleonic times to the Middle Ages to the early 1900s, to the time of Legends and the Fortress of Ultimate Darkness where they confront Evil.'),
(134, 'Torrente 4', 2011, 'Spain', 'Acción, Comedia, Policíaca', '1417108', '5,4  (3153 votos)', ''),
(135, 'Torrente 5. Operación Eurovegas', 2014, 'Spain', 'Acción, Comedia', '3321428', '5,4  (1714 votos)', 'Crooked cop Torrente gets out of jail in the year 2018 to find a different Spain from the one he knew.'),
(136, 'Toy Story That Time Forgot', 2014, 'USA', 'Animación, Cortos', '3473654', '7,3  (2438 votos)', 'The story takes place after a Christmas holiday with the regular toys finding themselves trapped in unusual territory with a group of new and delusional action figures. Together they must find their way back to their child"s bedroom and to safety.'),
(138, 'Transformers: Dark of the Moon', 2011, 'USA', 'Acción, Aventuras, Ciencia Ficción', '1399103', '6,3  (290639 votos)', 'Autobots Bumblebee, Ratchet, Ironhide, Mirage (aka Dino), Wheeljack (aka Que) and Sideswipe led by Optimus Prime, are back in action taking on the evil Decepticons, who are eager to avenge their recent defeat. The Autobots and Decepticons become involved in a perilous space race between the United States and Russia, to reach a hidden Cybertronian spacecraft on the moon and learn its secrets, and once again Sam Witwicky has to come to the aid of his robot friends. The new villain Shockwave is on the scene while the Autobots and Decepticons continue to battle it out on Earth.'),
(140, 'Turbo', 2013, 'USA', 'Comedia, Aventuras, Animación, Familiar, Deportes', '1860353', '6,5  (52719 votos)', 'From the makers of MADAGASCAR and KUNG FU PANDA, TURBO is a high-velocity 3D comedy about a snail who dares to dream big - and fast. After a freak accident infuses him with the power of super-speed, Turbo kicks into overdrive and embarks on an extraordinary journey to achieve the seemingly impossible: competing in the world"s fastest race, the Indianapolis 500. With the help of his tricked-out streetwise snail crew, this ultimate underdog puts his heart and shell on the line to prove that no dream is too big, and no dreamer too small.'),
(141, 'Tower Heist', 2011, 'USA', 'Acción, Comedia, Policíaca', '471042', '6,2  (100880 votos)', 'Josh Kovacs is the manager of a residential apartment in New York. He is close to all the tenants, especially Arthur Shaw, a financier. One day Shaw is arrested by the FBI for fraud. Josh thinks it"s a misunderstanding that can be resolved. But later he learns that the employees" pension fund which he asked Shaw to handle is gone. When one of the employees tries to kill himself, Josh"s views of Shaw change. He goes to see him and loses his temper. He loses his job. The FBI agent in charge of Shaw tells him that Shaw might walk and recovering the pension fund is unlikely. She tells him that it"s been rumored that Shaw has $20 million lying around if he needs it in a hurry. Josh thinks he knows where it is. So with two other employees who also lost their jobs and an evicted tenant, they set out to get into Shaw"s penthouse to get the money. But they realize they need the assistance of someone who knows how to steal. So Josh asks a guy he knows is a thief named Slide to help them.'),
(142, 'Underworld: Next Generation', 2012, 'USA', 'Acción, Terror', '3717252', '', 'Last chapter. Vampires and Lycans regain original forces to create a new species of half breeds created by Alexander Corvinus. Michael regains his memories and searches for Selene and his daughter. Humans and the new species live in a new peace.'),
(145, 'Warm Bodies', 2013, 'USA', 'Terror, Comedia, Romántica', '1588173', '6,9  (163753 votos)', 'With much of the world"s population now an undead horde, R is a young and oddly introspective zombie. While fighting with and feeding on a human scavenger party, R meets Julie and feels an urge to protect her. What happens next is the beginning of a strangely warm relationship that allows R to begin regaining his humanity. As this change spreads through the local undead population like a virus, Julie and R eventually have to face a larger issue when the very nature of their friendship is challenged. Caught between the paranoid human forces and the ferocious "Bonies", zombies who are a mutual threat, R and Julie must find a way to bridge the differences of each side to fight for a better world no one thought possible.'),
(146, 'World War Z', 2013, 'USA', 'Acción, Aventuras, Terror, Ciencia Ficción, Suspenso', '816711', '7,0  (388690 votos)', 'Life for former United Nations investigator Gerry Lane and his family seems content. Suddenly, the world is plagued by a mysterious infection turning whole human populations into rampaging mindless zombies. After barely escaping the chaos, Lane is persuaded to go on a mission to investigate this disease. What follows is a perilous trek around the world where Lane must brave horrific dangers and long odds to find answers before human civilization falls.'),
(147, 'X-Men: Days of Future Past', 2014, 'USA', 'Acción, Aventuras, Ciencia Ficción, Suspenso', '1877832', '8,1  (396443 votos)', 'Sentinels, robots that were created for the purpose of hunting down mutants were released in 1973. 50 years later the Sentinels would also hunt humans who aid mutants. Charles Xavier and his X-Men try their best to deal with the Sentinels but they are able to adapt and deal with all mutant abilities. Charles decides to go back in time and change things. He asks Kitty Pryde who can send a person"s consciousness into the person"s past to send him but she can only send someone back a few weeks because if she sends someone back further it could harm them. So Logan decides to go back himself because he might be able to withstand it. So Charles tells him that it"s Mystique who"s responsible because when she learned about the Sentinels she sought out Bolivar Trask the man who created them and killed him. She would be caught and studied and her ability to change was somehow added to the Sentinels which is why they can adapt. Logan must go to the younger Charles and ask him to help'),
(148, 'X-Men. La decisión final', 2006, 'Canada', 'Acción, Aventuras, Ciencia Ficción, Suspenso', '376994', '6,8  (328951 votos)', 'It has been several months since The X-Men stopped William Stryker, but that victory came at a price: they have lost Jean Grey when she tried to save them from the collapsed reservoir. Scott Summers (Cyclops) is still grieving about her loss. One day, he comes out to the place where Jean Grey sacrificed herself. Jean Grey appears right in front of him. Meanwhile, the rift between humans and mutants has finally reached the boiling point. Humans have discovered what causes humans to mutate and have found a cure for the mutation. The X-Men are appalled at this idea. When news about the cure comes to Magneto, he decides to organize an army of mutants and wage his war against the humans. When Jean Grey evolves into the Phoenix, her new mutant powers are so strong that she can not control her own body. Then, she kills off Professor X with her new powers. Now, The X-Men must stop Magneto again and put an end to the war against the humans, as well as stop Jean Grey"s Phoenix powers.'),
(149, 'Zipi y Zape y el club de la canica', 2013, 'Spain', 'Comedia, Aventuras, Familiar', '2388821', '5,5  (450 votos)', 'Naughty twins Zip & Zap are punished and sent to summer school at Hope, a strict re-education center run by Falconetti, who rules with a heavy hand and an eyepatch and forbids all forms of recreation and entertainment. They form the Marble Gang, the children"s Resistance, in order to defy the evil headmaster. Guided by intelligence, bravery and unbreakable faith in friendship, they uncover a mysterious secret hidden deep within the school and end up having the most exciting adventure of their lives.'),
(150, 'World"s End, The', 2013, 'UK', 'Acción, Ciencia Ficción, Comedia', '1213663', '7,0  (150561 votos)', '20 years after attempting an epic pub crawl, five childhood friends reunite when one of them becomes hell bent on trying the drinking marathon again. They are convinced to stage an encore by mate Gary King, a 40-year old man trapped at the cigarette end of his teens, who drags his reluctant pals to their home town and once again attempts to reach the fabled pub, The World"s End. As they attempt to reconcile the past and present, they realize the real struggle is for the future, not just theirs but humankind"s. Reaching The World"s End is the least of their worries.'),
(151, 'Patema y el mundo inverso', 2013, 'Japan', 'Animación, Aventuras, Drama, Fantasía, Ciencia Ficción', '2981768', '7,3  (1665 votos)', 'A young girl, from a civilization that resides in deep underground tunnels, finds herself trapped in an inverted world and teams up with a resident to escape and return home.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `prestamos`
--

DROP TABLE IF EXISTS `prestamos`;
CREATE TABLE IF NOT EXISTS `prestamos` (
  `id_pelicula` int(11) NOT NULL,
  `NumeroEjemplar` int(11) NOT NULL,
  `DNIUsuario` int(11) NOT NULL,
  `FechaPrestamo` date NOT NULL,
  `FechaDevolucion` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `DNI` int(11) NOT NULL,
  `Nombre` varchar(50) COLLATE utf8_bin NOT NULL,
  `Apellido` varchar(50) COLLATE utf8_bin NOT NULL,
  `Penalizacion` int(11) NOT NULL,
  `email` varchar(50) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`DNI`, `Nombre`, `Apellido`, `Penalizacion`, `email`) VALUES
(5036787, 'Natalia', 'Velayos', 0, 'pincr@gmail.com'),
(5038544, 'Cristina', 'Pérez', 0, 'creduarsa@hotmail.com'),
(5042008, 'Mónica', 'Diego', 0, 'monicatito_alsa@hotmail.es'),
(5062544, 'María', 'Molinero', 0, 'mariiiappe@hotmail.es'),
(5063999, 'María', 'Bárcena ', 0, 'pild.f.n.b@hotmail.com'),
(5076549, 'Emma', 'Sánchez', 0, 'lecris.l@hotmail.com'),
(5082350, 'María', 'González', 0, 'maria_mcril@'),
(5084859, 'Patricia', 'Núñez', 0, 'patricblad@hotmail.com'),
(5090534, 'Julieth', 'Alcaide', 0, 'yulfem@gmail.com'),
(5092275, 'Paloma', 'Jiménez ', 0, 'palomitjosk@hotmail.com'),
(5093988, 'Ana', 'Navarro', 0, 'anita_8letiile@hotmail.com'),
(5095348, 'Iris', 'Sánchez', 0, 'wiscarpi@hotmail.com'),
(5113989, 'Marta', 'Pérez', 0, 'marvicj@gmail.com'),
(5114311, 'María', 'Pato', 0, 'catalsebac@gmail.com'),
(5122976, 'Leticia', 'Del', 0, 'leticd.alamoand@gmail.com'),
(5135770, 'Blanca', 'Gregorio', 0, 'blanksr.lj@yahoo.es'),
(5181209, 'Natalia', 'Rumbero', 0, 'natijjcojj.@hotmail.com'),
(5188947, 'Bárbara', 'Serrano', 0, 'baelenitaa@gmail.com'),
(5194726, 'Laura', 'Jiménez ', 0, 'lala25_meri@hotmail.com'),
(5197050, 'Marija', 'Salas', 0, 'maria_fana@hotmail.com'),
(5197959, 'Cristina', 'Otero', 0, 'crimenchu-fe@gmail.com'),
(5199608, 'Raquel', 'Merino', 0, 'raqucarl@hotmail.com'),
(5200900, 'Ángela', 'Tizón', 0, 'palomitjuangoma@hotmail.com'),
(5202925, 'Miriam', 'Torras', 0, 'mileyrekaraq@terra.es'),
(5227016, 'Alba', 'Castaño', 0, 'shalsequcel@gmail.com'),
(5229280, 'Bárbara', 'Ibrahim', 0, 'barianjtem@hotmail.com'),
(5243144, 'Marta', 'González', 0, 'marandre@hotmail.com'),
(5245108, 'Alba', 'Criado ', 0, 'smile._pati_tgu@hotmail.com'),
(5247677, 'Carmen', 'Alonso', 0, 'menchu-jecl@hotmail.com'),
(5266386, 'Florencia', 'Garrudo', 0, 'fldmjb@hotmail.com'),
(5276787, 'Tamara', 'Martín ', 0, 'tamsandragk@hotmail.com'),
(5277660, 'Sandra', 'Díaz', 0, 'samlemmc@hotmail.com'),
(5283714, 'Miriam', 'Rivera', 0, 'mirihasasfs@gmail.com'),
(5306571, 'Esther', 'Molina', 0, 'divcar@hotmail.com'),
(5316998, 'Bárbara', 'Muñoz', 0, 'barbsanro@hotmail.com'),
(5331756, 'Ana', 'Garrido ', 0, 'anajesusis@yahoo.es'),
(5334494, 'María', 'Muñoz', 0, 'mpasergi@hotmail.com'),
(5346788, 'Iris', 'Rodríguez ', 0, 'wisi_immfea@hotmail.com'),
(5356882, 'Miriam', 'Sánchez ', 0, 'mimialex.tr@hotmail.com'),
(5364699, 'Julia', 'Espinosa', 0, 'jumery@hotmail.com'),
(5380545, 'Rocío', 'Ramos', 0, 'rociomikybav@hotmail.com'),
(5381627, 'Ana', 'Sánchez', 0, 'anita_8rebeca_nov@hotmail.com'),
(5384472, 'Laura', 'Ramos', 0, 'l.majose-gas@hotmail.com'),
(5396457, 'Coral', 'García', 0, 'coralitjropambe@hotmail.com'),
(5405558, 'Zaida', 'Villahermosa', 0, 'zaigualmt@outlook.com'),
(5406037, 'Patricia', 'Lamus', 0, 'patri_luis.so@icam.es'),
(5413432, 'Sandra', 'Pérez', 0, 'sandramap@gmail.com'),
(5415619, 'Patricia', 'Pérez', 0, 'oh_mysamib@hotmail.com'),
(5424388, 'María', 'Domínguez', 0, 'papasa@gmail.com'),
(5424614, 'Marija', 'López', 0, 'maria_sm@hotmail.com'),
(5430593, 'Brenda', 'Vera', 0, 'karafaelmo@gmail.com'),
(5452272, 'Esther', 'Casals', 0, 'divivipealv@gmail.com'),
(5460626, 'Julián', 'Gómez', 0, 'julianjabes@outlook.com'),
(5461000, 'Sonia', 'Ozores', 0, 'amyxoetcar@hotmail.com'),
(5463432, 'Laura', 'Sánchez', 0, 'laubednialpa@gmail.com'),
(5480834, 'Dolores', 'Domínguez', 0, 'thosevi@hotmail.com'),
(5492048, 'Alicia', 'Ortiz', 0, 'aliciauale@gmail.com'),
(5494242, 'Marta', 'Bonilla', 0, 'mqsluasamarz@hotmail.com'),
(5517411, 'Irene', 'Gil', 0, 'ipozojamyxopjos@arrakis.es'),
(5519386, 'Rocío', 'Rayo', 0, 'rocmgc2@hotmail.com'),
(5521323, 'Jennifer', 'García', 0, 'jenl.j@live.com'),
(5539084, 'Julia', 'Quemada', 0, 'julrocio.r@hotmail.com'),
(5542916, 'Sara', 'García ', 0, 'sara_nocareva@hotmail.com'),
(5557888, 'Saray', 'Martín ', 0, 'sarmiguel_s@hotmail.com'),
(5581903, 'Sonia', 'Alarcón', 0, 'amynurilok@gmail.com'),
(5585308, 'Elisa', 'Bustamante', 0, 'elisa_gsup@hotmail.com'),
(5592363, 'Paula', 'Cañal', 0, 'paula_segucla@hotmail.com'),
(5605265, 'Lara', 'Fernández', 0, 'lavictor1a@hotmail.com'),
(5606750, 'Natalia', 'Dávila', 0, 'nalauritapq@aol.com'),
(5614749, 'María', 'Bartolomé', 0, 'pab9maalb@gmail.com'),
(5620206, 'Natalia', 'Moya', 0, 'natmqslj@gmail.com'),
(5639283, 'Jennifer', 'Lago', 0, 'jeny-gebolr@msn.com'),
(5663112, 'Desirée', 'Esteban', 0, 'd.asamarades@hotmail.com'),
(5672261, 'Bárbara', 'Grande', 0, 'barbaedu@gmail.com'),
(5681162, 'Ana', 'Fernández', 0, 'anaanitavp@hotmail.com'),
(5691358, 'Elisabeth', 'Torras', 0, 'elyy.g1agar@nvr-edificios.com'),
(5691483, 'Patricia', 'Fernández', 0, 'patbusto@gmail.com'),
(5699043, 'Miriam', 'Cruz', 0, 'mimigogalejage@hotmail.com'),
(5700152, 'Nuria', 'Baselga', 0, 'petirojsa@hotmail.com'),
(5701553, 'Sandra', 'López', 0, 'sanaceandi_a@gmail.com'),
(5706379, 'Carla', 'Sánchez', 0, 'karlisafh@gmail.com'),
(5707197, 'Leticia', 'González', 0, 'leti_malmueg@gmail.com'),
(5715875, 'Blanca', 'Cruz', 0, 'blancafepab@gmail.com'),
(5721105, 'María', 'Fondo', 0, 'malarjpanesvm@hotmail.com'),
(5731402, 'Marta', 'Lara', 0, 'mmccragu@telefonica.net'),
(5733090, 'María', 'Ramos', 0, 'madmamigocr@hotmail.com'),
(5737019, 'Miriam', 'Wasmer', 0, 'mimigognua.@hotmail.com'),
(5739248, 'María', 'Álvarez', 0, 'carmemlagoelik@hotmail.com'),
(5778450, 'Sara', 'Casanova', 0, 'sara_ljabj@hotmail.com'),
(5779295, 'Alba', 'Prudencio ', 0, 'almara4miguelal@hotmail.com'),
(5800443, 'Elena', 'Espeso', 0, 'elenicrhel@gmail.com'),
(5806314, 'Alba', 'León', 0, 'smalfon1mar@hotmail.com'),
(5814581, 'Sara', 'Reina', 0, 'sfpilarfr@hotmail.com'),
(5823230, 'Nuria', 'Sánchez', 0, 'nuriavzoek993adr@hotmail.com'),
(5832306, 'Iris', 'Álvarez ', 0, 'wisi_imal@hotmail.com'),
(5851903, 'Tamara', 'Panes', 0, 't.yusriki.s@gmail.com'),
(5857921, 'Ruth', 'López', 0, 'rutpabalf@hotmail.com'),
(5861462, 'Sara', 'Moreno', 0, 'sfsarabazo@hotmail.com'),
(5871845, 'Bárbara', 'Pérez', 0, 'barbarablanka_@gmail.com'),
(5872666, 'Beatriz', 'Añón', 0, 'bgermigubel@hotmail.com'),
(5882617, 'Bárbara', 'Jiménez ', 0, 'babdebenim@hotmail.com'),
(5885888, 'Marta', 'Pérez', 0, 'mar_ttito_@hotmail.com'),
(5894682, 'Paula', 'Molina', 0, 'p.mari@gmail.com'),
(5894740, 'Patricia', 'Martín', 0, 'patrifhcop@hotmail.com'),
(5897059, 'Carla', 'Diz', 0, 'kacarlot@hotmail.com'),
(5897265, 'Marta', 'Merani', 0, 'martamjohn-asm@hotmail.com'),
(5899301, 'Miriam', 'Núñez', 0, 'mihelemi@hotmail.es'),
(5900192, 'Irene', 'Jiménez', 0, 'irene.dardam@hotmail.com'),
(5921677, 'Saray', 'Pizarro ', 0, 'saraipio@gmail.com'),
(5923485, 'Amelia', 'Luján', 0, 'amelikerm@hotmail.com'),
(5928536, 'Laura', 'Torras', 0, 'lauraguericnav@hotmail.com'),
(5936978, 'Isabella', 'González', 0, 'isaalvame@live.com'),
(5938319, 'Irene', 'García', 0, 'irmak@gmail.com'),
(5945747, 'Marta', 'Valero', 0, 'sanchpean@hotmail.com'),
(5951912, 'María', 'Díaz', 0, 'masama@hotmail.com'),
(5953688, 'Carlota', 'Bueno', 0, 'carlomaria_aa@msn.com'),
(5964985, 'Susana', 'Gómez', 0, '1asa@hotmail.es'),
(5966510, 'Marta', 'Pérez', 0, 'martfatimitl@gmail.com'),
(5968219, 'Patricia', 'Suarez', 0, 'patrmaria_ch@hotmail.com'),
(5971530, 'Carla', 'Muñoz', 0, 'karlsergin@nvr-edificios.com'),
(5973839, 'Alejandra', 'Francisco', 0, 'alegalaubeda@hotmail.com'),
(5983285, 'Estefanía', 'Estrada', 0, 'fannmartuxal@hotmail.com'),
(5992988, 'Natalia', 'Kostova', 0, 'nsmiriamosc@gmail.com');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `peliculas`
--
ALTER TABLE `peliculas`
 ADD PRIMARY KEY (`id_pelicula`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
 ADD PRIMARY KEY (`DNI`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
